import Head from "next/head";
import HomeComponent from "../components/Home";
export default function Home() {

  return (
    <>
      <Head>
        <title>Kumo connect</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {/* <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
           Welcome {session ? session.user.name : "Guest"}
          </h1> */}
          <HomeComponent />
        </div>
      </main>
    </>
  );
}
